### ISSUE TITLE
i got the trip planner error in crew ai 

### ISSUE THREAD

**Issue by Narender-007** [bhancockio/crew-ai-crash-course#1]
please can you give me solution 

What is the date range you are interested in traveling?
may 2024

What are some of your high level interests and hobbies?
ai,latest technologies
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\narender_workspace\test_python\crew-ai-crash-course-master\main.py", line 90, in <module>
    result = trip_crew.run()
             ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\narender_workspace\test_python\crew-ai-crash-course-master\main.py", line 28, in run
    plan_itinerary = tasks.plan_itinerary(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\narender_workspace\test_python\crew-ai-crash-course-master\tasks.py", line 52, in plan_itinerary
    return Task(
           ^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\crewai\task.py", line 100, in __init__
    super().__init__(**config, **data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Task
expected_output
  Field required [type=missing, input_value={'description': "\n**Task...ng travel iteneraries.)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by roypeter** [comment]
+1, Same error

**Comment by Narender-007** [comment]
> +1, Same error

add expected_output key in your task then execute the file.
