### ISSUE TITLE
Trying to update to latest crewai version

### ISSUE THREAD

**Issue by thiagolocatelli** [bhancockio/crew-ai-crash-course#3]
Hello there. Thanks for this great crash course. I was trying to update to the latest crewai version `0.30.11` and I keep getting a Pydantic error:

```
## Welcome to Trip Planner Crew
-------------------------------

From where will you be traveling from?
Austin, TX

What are the cities options you are interested in visiting?
Sedona, AZ

What is the date range you are interested in traveling?
from July 20th to July 27th

What are some of your high level interests and hobbies?
Hiking
Traceback (most recent call last):
  File "/Users/thiago/Develop/python/crewai/crew-ai-crash-course/main.py", line 90, in <module>
    result = trip_crew.run()
             ^^^^^^^^^^^^^^^
  File "/Users/thiago/Develop/python/crewai/crew-ai-crash-course/main.py", line 28, in run
    plan_itinerary = tasks.plan_itinerary(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thiago/Develop/python/crewai/crew-ai-crash-course/tasks.py", line 52, in plan_itinerary
    return Task(
           ^^^^^
  File "/Users/thiago/Library/Caches/pypoetry/virtualenvs/trip-planner-yt-q783y_bj-py3.11/lib/python3.11/site-packages/crewai/task.py", line 102, in __init__
    super().__init__(**config, **data)
  File "/Users/thiago/Library/Caches/pypoetry/virtualenvs/trip-planner-yt-q783y_bj-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Task
expected_output
  Field required [type=missing, input_value={'description': "\n**Task...ng travel iteneraries.)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
```

Any idea on how to fix this? New to AI and Python, so any help is greatly appreacited.

**Comment by LibertyAPI** [comment]
You have to add parameter "expected_output" in Task() inside the tasks.py files
